# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

highlighter: pygments

destination: ../www
baseurl: /www

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  
# Build settings
markdown: kramdown

# Setup
title:               Cloud Spotter
tagline:             'Technical Investigations in Scale'
description:         'Bringing the AweSome to AWS since 2011'
url:                 https://github.com/danmiley/danmiley.github.io
paginate:            5

# About/contact
author:
  name:              Dan Miley
  url:               https://twitter.com/danmiley
  email:             dmiley@adobe.com

# Custom vars
version:             1.0.0

