# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

highlighter: pygments

destination: ../www
baseurl: /www

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  
# Build settings
markdown: kramdown

# Setup
title:               Daily Doppio
tagline:             'Peramulations'
description:         'Bringing the Awesome since 2015'
url:                 http://danmiley.gethub.com
paginate:            5

# About/contact
author:
  name:              Dan Miley
  url:               https://twitter.com/danmiley
  email:             dan.miley@gmail.com

# Custom vars
version:             1.0.0

